title: Nithin Jacob
logo: /assets/img/logo.jpg
description: 
  <p align="center">
  <a href="pdf/resume.pdf">Resume</a> |
  <a href="https://www.linkedin.com/in/Nithin-Jacob/">LinkedIn</a> |
  <a href="https://github.com/Nithin-Jacob">GitHub</a>
  
  <br>   
I am an instrumentation engineer working in testing field in aerospace industry.

  <br>
  </p>
show_downloads: false
google_analytics:
theme: jekyll-theme-minimal
